# Generated by Django 3.0.6 on 2020-05-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_imgmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgModel',
        ),
    ]
